version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - HF_MODEL_ID=microsoft/phi-2
      - HF_DEVICE=cuda
      - HF_MAX_NEW_TOKENS=512
      - DATABASE_URL=sqlite:///./topicLens.db
      - SERPSHOT_API_KEY=5bff7fc157df396b31466b9f0951a485
      - DISPLAY=:99
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./backend:/app
      - huggingface_cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  worker:
    build: ./backend
    command: bash -c "Xvfb :99 -screen 0 1920x1080x24 -nolisten tcp & sleep 2 && celery -A tasks worker --loglevel=info --concurrency=4"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - HF_MODEL_ID=microsoft/phi-2
      - HF_DEVICE=cuda
      - HF_MAX_NEW_TOKENS=512
      - DATABASE_URL=sqlite:///./topicLens.db
      - SERPSHOT_API_KEY=5bff7fc157df396b31466b9f0951a485
      - DISPLAY=:99
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./backend:/app
      - huggingface_cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  huggingface_cache:
